spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proto
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none