spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/proto
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true
    secondary:
      url: jdbc:mysql://localhost:3306/proto
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
